CREATE TABLE "combat_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combat_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"encounter_id" uuid NOT NULL,
	"timestamp" timestamp NOT NULL,
	"event_type" text NOT NULL,
	"source_player_id" uuid,
	"target_player_id" uuid,
	"spell_id" integer,
	"amount" integer,
	"is_crit" boolean
);
--> statement-breakpoint
CREATE TABLE "encounters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"raid_id" uuid NOT NULL,
	"boss_name" text NOT NULL,
	"zone_id" integer,
	"kill" boolean,
	"start_time" timestamp NOT NULL,
	"end_time" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "players" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"class" text
);
--> statement-breakpoint
CREATE TABLE "raids" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"custom_name" text NOT NULL,
	"guild_name" text,
	"uploader_id" text,
	"start_time" timestamp,
	"end_time" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "combat_events" ADD CONSTRAINT "combat_events_encounter_id_encounters_id_fk" FOREIGN KEY ("encounter_id") REFERENCES "public"."encounters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "combat_events" ADD CONSTRAINT "combat_events_source_player_id_players_id_fk" FOREIGN KEY ("source_player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "combat_events" ADD CONSTRAINT "combat_events_target_player_id_players_id_fk" FOREIGN KEY ("target_player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_raid_id_raids_id_fk" FOREIGN KEY ("raid_id") REFERENCES "public"."raids"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "combat_events_encounter_id_idx" ON "combat_events" USING btree ("encounter_id");--> statement-breakpoint
CREATE INDEX "combat_events_timestamp_idx" ON "combat_events" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "encounters_raid_id_idx" ON "encounters" USING btree ("raid_id");--> statement-breakpoint
CREATE INDEX "encounters_boss_name_idx" ON "encounters" USING btree ("boss_name");--> statement-breakpoint
CREATE INDEX "players_name_idx" ON "players" USING btree ("name");--> statement-breakpoint
CREATE INDEX "raids_custom_name_idx" ON "raids" USING btree ("custom_name");--> statement-breakpoint
CREATE INDEX "raids_guild_name_idx" ON "raids" USING btree ("guild_name");